Repository lightninglabs/lightning-terminal, pull requests merged in 2025-02, with the labels that each got.

#960 GitHub: build nightly docker image from master
  .github/workflows/docker.yml
Labels: no-changelog

#967 [sql-9] sessions: small sql preparations
  session/db.go
  session/errors.go
  session/kvdb_store.go
  session_rpcserver.go
  terminal.go
Labels: no-changelog, sql-ize

#968 [sql-10] sessions: decouple super macaroon helpers from `sessions` package
  accounts/rpcserver.go
  cmd/litcli/helpers.go
  itest/litd_firewall_test.go
  macaroons/macaroons.go
  macaroons/super_mac.go
  macaroons/super_mac_test.go
  rpc_proxy.go
  session/interface.go
  session/macaroon.go
  session_rpcserver.go
  terminal.go
Labels: no-changelog, sql-ize

#970 [sql-12] sessions: make ListSession methods SQL ready
  session/interface.go
  session/kvdb_store.go
  session/store_test.go
  session_rpcserver.go
Labels: no-changelog, sql-ize

#978 itest: ensure peer is connected before channel open
  itest/litd_firewall_test.go
Labels: no-changelog

#977 golangci: enable line length linter
  .golangci.yml
  autopilotserver/client.go
  config.go
  firewall/config.go
  firewall/privacy_mapper_test.go
  rpcmiddleware/config.go
  subservers/config.go
Labels: no-changelog

#971 [sql-13] sessions: set up for atomic session creation
  app/src/types/generated/lit-sessions_pb.d.ts
  app/src/types/generated/lit-sessions_pb.js
  litrpc/lit-autopilot.swagger.json
  litrpc/lit-sessions.pb.go
  litrpc/lit-sessions.proto
  litrpc/lit-sessions.swagger.json
  proto/lit-sessions.proto
  session/interface.go
  session/kvdb_store.go
  session/store_test.go
  session_rpcserver.go
Labels: no-changelog, sql-ize

#981 accounts: Credit and debit accounts `kvdb` additions prep
  accounts/interface.go
  accounts/service.go
  accounts/store_kvdb.go
  accounts/store_test.go
Labels: no-changelog

#954 [sql-7] accounts: add SQL implementation of the accounts store
  .github/workflows/main.yml
  accounts/interface.go
  accounts/store_sql.go
  accounts/store_test.go
  accounts/test_kvdb.go
  accounts/test_postgres.go
  accounts/test_sqlite.go
  make/testing_flags.mk
Labels: database, no-changelog, sql-ize

#955 [sql-8]: run itests against all DB types
  .github/workflows/main.yml
  .golangci.yml
  config.go
  config_dev.go
  config_prod.go
  itest/litd_node.go
  make/testing_flags.mk
  terminal.go
Labels: database, no-changelog, tests, sql-ize

#980 [sql-14] sessions: atomic session creation
  session/interface.go
  session/kvdb_store.go
  session/store_test.go
  session_rpcserver.go
Labels: no-changelog, sql-ize

#984 [sql-15] sessions: various functional options for NewSession
  session/interface.go
  session/kvdb_store.go
  session/store_test.go
  session/tlv_test.go
  session_rpcserver.go
Labels: no-changelog, sql-ize

#988 [sql-17] sessions: test preparation
  itest/litd_firewall_test.go
  session/errors.go
  session/kvdb_store.go
  session/store_test.go
  session/test_kvdb.go
Labels: no-changelog, sql-ize

#986 [sql-16] sessions: update Store interface methods to take a context
  firewall/privacy_mapper.go
  firewall/rule_enforcer.go
  firewalldb/actions.go
  firewalldb/actions_test.go
  firewalldb/interface.go
  firewalldb/mock.go
  session/interface.go
  session/kvdb_store.go
  session/server.go
  session/store_test.go
  session_rpcserver.go
Labels: no-changelog, sql-ize
