Repository lightninglabs/lightning-terminal, pull requests merged in 2025-04, with the labels that each got.

#1024 buld: bump kvdb mod version
  go.mod
  go.sum
Labels: no-changelog, build

#1023 [sql-25] firewalldb: start cleaning up RulesDB/KVStores code
  config_dev.go
  config_prod.go
  firewalldb/actions.go
  firewalldb/actions_test.go
  firewalldb/db.go
  firewalldb/interface.go
  firewalldb/kvdb_store.go
  firewalldb/kvstores_kvdb.go
  firewalldb/kvstores_test.go
  firewalldb/privacy_mapper.go
  firewalldb/privacy_mapper_test.go
  firewalldb/test_kvdb.go
  session_rpcserver.go
  terminal.go
Labels: no-changelog

#1028 [sql-27]: db/sqlc: kvstores schemas & queries
  db/migrations.go
  db/sqlc/kvstores.sql.go
  db/sqlc/migrations/000003_kvstores.down.sql
  db/sqlc/migrations/000003_kvstores.up.sql
  db/sqlc/models.go
  db/sqlc/querier.go
  db/sqlc/queries/kvstores.sql
Labels: database, no-changelog, sql-ize

#1030 [sql-29]: firewalldb: implement SQL version of RulesDB (kvstores)
  config_dev.go
  firewalldb/kvstores_sql.go
  firewalldb/sql_store.go
  firewalldb/test_kvdb.go
  firewalldb/test_postgres.go
  firewalldb/test_sql.go
  firewalldb/test_sqlite.go
  session/sql_store.go
Labels: database, no-changelog, sql-ize

#1039 [sql-30] firewalldb: privacy mapper clean up in preparation for SQL impl
  firewalldb/privacy_mapper.go
  firewalldb/privacy_mapper_kvdb.go
  firewalldb/privacy_mapper_test.go
Labels: no-changelog, sql-ize

#995 Custom channels itest: Use group keys on some payments & invoices
  go.mod
  go.sum
  itest/assets_test.go
  itest/litd_custom_channels_test.go
  itest/litd_test_list_on_test.go
Labels: no-changelog

#1043 [sql-31] firewalldb: Privacy Mapper schemas, queries and CRUD
  db/migrations.go
  db/sqlc/migrations/000004_privacy_pairs.down.sql
  db/sqlc/migrations/000004_privacy_pairs.up.sql
  db/sqlc/models.go
  db/sqlc/privacy_paris.sql.go
  db/sqlc/querier.go
  db/sqlc/queries/privacy_paris.sql
  firewall/privacy_mapper.go
  firewall/privacy_mapper_test.go
  firewall/rule_enforcer.go
  firewalldb/db.go
  firewalldb/interface.go
  firewalldb/privacy_mapper.go
  firewalldb/privacy_mapper_kvdb.go
  firewalldb/privacy_mapper_sql.go
  firewalldb/privacy_mapper_test.go
  firewalldb/sql_store.go
  session_rpcserver.go
  terminal.go
Labels: no-changelog, sql-ize
